### ISSUE TITLE
Cannot get github-release-notes-generator.jar 

### ISSUE THREAD

**Issue by nmbsd** [Decathlon/release-notes-generator-action#23]
When I first saw this error it scared me. Use of Dropbox looked very suspicious. I thought it was trying to upload my repo code to dropbox. Actually it's trying to download `github-release-notes-generator.jar`.

Why bother trying to download the jar? How about you include (COPY) a default version of `github-release-notes-generator.jar` into the Docker image while it is being built? Then if `RELEASE_NOTE_GENERATOR_VERSION` is defined then attempt to download the version at run-time. And preferably stop using Dropbox too.

```
Step 9/11 : RUN chmod +x JSON.sh &&     wget -O github-release-notes-generator.jar https://ucd1f7512113b0c593d98dba7d90.dl.dropboxusercontent.com/cd/0/get/BFU15LNNmRHvWpIeQ31s3JxWsc1L2JnBNmTEcj_6zJbELHm4QcZLQe8dQC5CXtesNJPdUIYT-hu7E6kmEX40As8Sogi4_XkTX3-mnFecFusHfSTLQhbKD9eZPp-NbOldrzw/file?dl=1#
   ---> Running in 5aacb39b2313
  Connecting to ucd1f7512113b0c593d98dba7d90.dl.dropboxusercontent.com (162.125.3.15:443)
  wget: server returned error: HTTP/1.1 404 Not Found
  The command '/bin/sh -c chmod +x JSON.sh &&     wget -O github-release-notes-generator.jar https://ucd1f7512113b0c593d98dba7d90.dl.dropboxusercontent.com/cd/0/get/BFU15LNNmRHvWpIeQ31s3JxWsc1L2JnBNmTEcj_6zJbELHm4QcZLQe8dQC5CXtesNJPdUIYT-hu7E6kmEX40As8Sogi4_XkTX3-mnFecFusHfSTLQhbKD9eZPp-NbOldrzw/file?dl=1#' returned a non-zero code: 1
```

**Comment by mmornati** [comment]
Yeah sorry about that. We used something to download a prebuilt version of the jar containing a fix we needed (spring-boot version upgrade). 
We will remove this dropbox part once the plugin will be released with the necessary fix.

**Comment by lfgcampos** [comment]
Hey @mmornati, spring released the new version with the fix we needed back there and I saw you already updated the project. Thank you very much!
Are you planning for a release soon?
