### ISSUE TITLE
Add Filename variable that can be used when triggered by 'workflow_dispatch'

### ISSUE THREAD

**Issue by derTobsch** [Decathlon/release-notes-generator-action#28]
It would be nice to use the `USE_MILESTONE_TITLE: "true"` if the the workflow was triggered by `workflow_dispatch`. Or do define the complete name of the markdown file with a new variable to set the name via the properties given by the `workflow_dispatch` trigger.

I added a PR #29 to add a own Filename

**Comment by mmornati** [comment]
Thanks man. Going to check it out.
