### ISSUE TITLE
Output folder cannot be created if exists and action fails

### ISSUE THREAD

**Issue by derTobsch** [Decathlon/release-notes-generator-action#30]
If the `OUTPUT_FOLDER` is configured and does already exist, than the action runs into an error, because https://github.com/Decathlon/release-notes-generator-action/blob/master/entrypoint.sh#L60 `mkdir $OUTPUT_FOLDER` cannot run. We need a guard to check if the folder is already there or not.

Error message:
```
mkdir: can't create directory '.chglog': File exists
```

So we could replace the line with
```
[ ! -d "$OUTPUT_FOLDER" ] && mkdir $OUTPUT_FOLDER"
```

**Comment by derTobsch** [comment]
*ping* :)

**Comment by derTobsch** [comment]
Sorry for bothering you. This is "blocking" our releases. Is there any chance that this will be available soon? :)

**Comment by mmornati** [comment]
Sorry about the delay... Do not know why my Github notification is not always sending me notification about this repository 😢
We can quickly move on to unblock you, sorry.
As I put in the PR comment we can even completely skip the folder creation.

**Comment by derTobsch** [comment]
Take a look at the top of the repo and change the watch mode to 'All Activity'. Maybe that will help you :)
